package ORM;
// Generated 13-feb-2020 9:48:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String dni;
     private String nomEmp;
     private Set asigProys = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String dni, String nomEmp) {
        this.dni = dni;
        this.nomEmp = nomEmp;
    }
    public Empleado(String dni, String nomEmp, Set asigProys) {
       this.dni = dni;
       this.nomEmp = nomEmp;
       this.asigProys = asigProys;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }
    public Set getAsigProys() {
        return this.asigProys;
    }
    
    public void setAsigProys(Set asigProys) {
        this.asigProys = asigProys;
    }




}


