package ORM;
// Generated 13-feb-2020 9:48:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProy;
     private String nomProy;
     private Date FInicio;
     private Date FFin;
     private Set asigProys = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(String nomProy, Date FInicio) {
        this.nomProy = nomProy;
        this.FInicio = FInicio;
    }
    public Proyecto(String nomProy, Date FInicio, Date FFin, Set asigProys) {
       this.nomProy = nomProy;
       this.FInicio = FInicio;
       this.FFin = FFin;
       this.asigProys = asigProys;
    }
   
    public Integer getIdProy() {
        return this.idProy;
    }
    
    public void setIdProy(Integer idProy) {
        this.idProy = idProy;
    }
    public String getNomProy() {
        return this.nomProy;
    }
    
    public void setNomProy(String nomProy) {
        this.nomProy = nomProy;
    }
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }
    public Set getAsigProys() {
        return this.asigProys;
    }
    
    public void setAsigProys(Set asigProys) {
        this.asigProys = asigProys;
    }




}


