package ORM;
// Generated 13-feb-2020 1:27:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProy;
     private Empleado empleado;
     private String nomProy;
     private Date FInicio;
     private Date FFin;

    public Proyecto() {
    }

	
    public Proyecto(Empleado empleado, String nomProy, Date FInicio) {
        this.empleado = empleado;
        this.nomProy = nomProy;
        this.FInicio = FInicio;
    }
    public Proyecto(Empleado empleado, String nomProy, Date FInicio, Date FFin) {
       this.empleado = empleado;
       this.nomProy = nomProy;
       this.FInicio = FInicio;
       this.FFin = FFin;
    }
   
    public Integer getIdProy() {
        return this.idProy;
    }
    
    public void setIdProy(Integer idProy) {
        this.idProy = idProy;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getNomProy() {
        return this.nomProy;
    }
    
    public void setNomProy(String nomProy) {
        this.nomProy = nomProy;
    }
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }




}


