package ORM;
// Generated 12-feb-2020 19:36:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String dni;
     private String nomEmp;
     private Set pantillas = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String dni) {
        this.dni = dni;
    }
    public Empleado(String dni, String nomEmp, Set pantillas) {
       this.dni = dni;
       this.nomEmp = nomEmp;
       this.pantillas = pantillas;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }
    public Set getPantillas() {
        return this.pantillas;
    }
    
    public void setPantillas(Set pantillas) {
        this.pantillas = pantillas;
    }




}


