package ORM;
// Generated 6 feb. 2020 14:11:46 by Hibernate Tools 4.3.1



/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private int idLoc;
     private Provincia provincia;
     private String nomLoc;

    public Localidad() {
    }

    public Localidad(int idLoc, Provincia provincia, String nomLoc) {
       this.idLoc = idLoc;
       this.provincia = provincia;
       this.nomLoc = nomLoc;
    }
   
    public int getIdLoc() {
        return this.idLoc;
    }
    
    public void setIdLoc(int idLoc) {
        this.idLoc = idLoc;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNomLoc() {
        return this.nomLoc;
    }
    
    public void setNomLoc(String nomLoc) {
        this.nomLoc = nomLoc;
    }




}


