package ORM;
// Generated 13-feb-2020 0:49:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String dni;
     private Departamento departamento;
     private String nomEmp;
     private Set jefeProyectos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String dni, Departamento departamento, String nomEmp) {
        this.dni = dni;
        this.departamento = departamento;
        this.nomEmp = nomEmp;
    }
    public Empleado(String dni, Departamento departamento, String nomEmp, Set jefeProyectos) {
       this.dni = dni;
       this.departamento = departamento;
       this.nomEmp = nomEmp;
       this.jefeProyectos = jefeProyectos;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }
    public Set getJefeProyectos() {
        return this.jefeProyectos;
    }
    
    public void setJefeProyectos(Set jefeProyectos) {
        this.jefeProyectos = jefeProyectos;
    }




}


