package ORM;
// Generated 13-feb-2020 0:49:55 by Hibernate Tools 4.3.1



/**
 * JefeProyectoId generated by hbm2java
 */
public class JefeProyectoId  implements java.io.Serializable {


     private String dni;
     private int idProy;

    public JefeProyectoId() {
    }

    public JefeProyectoId(String dni, int idProy) {
       this.dni = dni;
       this.idProy = idProy;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getIdProy() {
        return this.idProy;
    }
    
    public void setIdProy(int idProy) {
        this.idProy = idProy;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JefeProyectoId) ) return false;
		 JefeProyectoId castOther = ( JefeProyectoId ) other; 
         
		 return ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) )
 && (this.getIdProy()==castOther.getIdProy());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         result = 37 * result + this.getIdProy();
         return result;
   }   


}


